### ISSUE TITLE
How mature is this

### ISSUE THREAD

**Issue by marcodejongh** [HokieGeek/btkb#5]
Hey HokieGeek,

Nice job on this project and all the diagrams, I was just wondering how mature is the project?
Do you have photos or more information on your end product? My biggest complaint about my pok3r is it not being wireless, so I'd be very keen to make mine wireless

**Comment by HokieGeek** [comment]
Not very. The only way I could make the design work with the size I wanted was with a 4 layer PCB which I do not wish to pay for :). So I mostly dropped this effort.
